### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nipunarora** [fsalem/Spark-Kafka-Writer#1]
@fsalem 
I am using your spark-kafka writer for my spark streaming application, and I am getting an error with "too many open files" problem.

What is the  proper way to close kafka producers?

```
public void writeToKafka(final JavaDStream<String> javaDStream, final String topic) {
		javaDStream.foreachRDD(new JavaRDDStringKafkaWriter(pool, topic,kafkaAsync));
	}
```

Any help will be really helpful. The following is the exception I get:

Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 85968.0 failed 1 times, most recent failure: Lost task 0.0 in stage 85968.0 (TID 29562, localhost): java.io.FileNotFoundException: /tmp/blockmgr-1b3ddc44-f9a4-42cd-977c-532cb962d7d3/3e/shuffle_10625_0_0.data.4651a131-6072-460b-b150-2b3080902084 (too many open files)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at org.apache.spark.storage.DiskBlockObjectWriter.open(DiskBlockObjectWriter.scala:88)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:181)
	at org.apache.spark.util.collection.WritablePartitionedPairCollection$$anon$1.writeNext(WritablePartitionedPairCollection.scala:56)
	at org.apache.spark.util.collection.ExternalSorter.writePartitionedFile(ExternalSorter.scala:659)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:72)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1857)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1870)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1883)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1954)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:920)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
	at org.apache.spark.api.java.JavaRDDLike$class.foreachPartition(JavaRDDLike.scala:225)
	at org.apache.spark.api.java.AbstractJavaRDDLike.foreachPartition(JavaRDDLike.scala:46)
	at org.necla.ngla.kafka.JavaRDDStringKafkaWriter.call(JavaRDDStringKafkaWriter.java:25)
	at org.necla.ngla.kafka.JavaRDDStringKafkaWriter.call(JavaRDDStringKafkaWriter.java:10)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$3.apply(JavaDStreamLike.scala:335)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$3.apply(JavaDStreamLike.scala:335)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:426)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:229)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:229)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:229)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /tmp/blockmgr-1b3ddc44-f9a4-42cd-977c-532cb962d7d3/3e/shuffle_10625_0_0.data.4651a131-6072-460b-b150-2b3080902084 (too many open files)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at org.apache.spark.storage.DiskBlockObjectWriter.open(DiskBlockObjectWriter.scala:88)
	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:181)
	at org.apache.spark.util.collection.WritablePartitionedPairCollection$$anon$1.writeNext(WritablePartitionedPairCollection.scala:56)
	at org.apache.spark.util.collection.ExternalSorter.writePartitionedFile(ExternalSorter.scala:659)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:72)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)

**Comment by fsalem** [comment]
@nipunarora,
Hello,

As far as I know, this exception is thrown when too many producers are opened at the same time. If you create an instance from "JavaDStreamKafkaWriterFactory", only 3 producers will be opened at the same time. Do you have other jobs that use the same topic with more producers?

A good way to close the producers is when the jobs are finished. You can do that in a Listener.

**Comment by nipunarora** [comment]
@fsalem 
I am unfortunately using this in spark streaming, so "close the producers" when jobs are finished doesn't work, because job does not finish technically.

Do you have a demo class which shows the use of JavaDStreamKafkaWriterFactory? I guess I am not using the factory. I am using the JavaRDDKafkaWriter directly.

Also would making the kafka producer pool a singleton work?

**Comment by nipunarora** [comment]
@fsalem 
Can you explain for the writer factory, why do we need to initiate consumers?
```

KafkaConsumerPool kafkaConsumerPool = new KafkaConsumerPool(3, config);
		javaDStream
				.context()
				.sparkContext()
				.addSparkListener(
						new SparkJobListener(kafkaConsumerPool,
								kafkaProducerPool,topic));
```
Shouldn't creating a kafka producerpool be enough?

**Comment by fsalem** [comment]
Hi,

Sorry for being late but I'm busy this week and the following one. Initiating a pool of consumers is just to enhance the performance. You can, of course, start with one consumer in the pool. Then and when needed, more consumers can be created. If you're using Spark streaming with Kafka, I believe that this project could help you "https://github.com/fsalem/Spark_Kafka_demo". Please check this file "https://github.com/fsalem/Spark_Kafka_demo/blob/master/src/spark/SparkKafkaStreamWordCount.java"

**Comment by nipunarora** [comment]
@fsalem 
I used your example and ran a Kafka Word Count example which sends it's output to kafka using the producer pool object created from the factory.

I created a function level trace, and verified that there is indeed a resource leak in terms of producer connections. They are being constantly re-created for each micro-batch (I am guessing because of deserialization of the pool object)

Below is a snapshot of the output

```
//This is the inital pool being created
creating Kafka Pool
Inside intialize function
creating producer
creating producer
creating producer
-------------------------------------------
Time: 1486510680000 ms
-------------------------------------------

-------------------------------------------
Time: 1486510680000 ms
-------------------------------------------

-------------------------------------------
Time: 1486510690000 ms
-------------------------------------------
hello
hello
...

-------------------------------------------
Time: 1486510690000 ms
-------------------------------------------
(hello,4)
(stupid,4)

// This is a copy being created (this happens whenever it writes to kafka)
Inside intialize function
creating producer
creating producer
creating producer
```

I have left the source code here:
https://github.com/nipunarora/Spark-Kafka-Writer

**Comment by nipunarora** [comment]
@fsalem 

Just an FYI the problem seems to be:

`private transient ConcurrentLinkedQueue<KafkaProducer<String, String>> pool;
`
transient by definition is not persistent across micro-batches, hence every subsequent micro-batch gets a null pool object.

The borrowProducer() in every microbatch gets an empty pool object, and hence creates new connections. These connections are never closed in a long running system.

```
public synchronized KafkaProducer<String, String> borrowProducer() {
   if (pool == null||pool.isEmpty()) {
      System.out.println("initialize pool");
      initialize();
   }
   KafkaProducer<String, String> object;
   if ((object = pool.poll()) == null) {
      object = createProducer();
   }

   return object;
}
```

Obviously, I can close connections in returnProducer() function, but that is a very heavy performance implementation. Is there anyway to re-use connections across micro-batches?

**Comment by timeLessmeng** [comment]
I also have the same problem with structured streaming readStream from kafka:
java.io.FileNotFoundException: /data/hadoop/yarn/local/usercache/hue/appcache/application_1568106731393_0586/blockmgr-d2b8076e-92c8-4f0c-a8a0-68b08b7b16de/21/temp_shuffle_f0801cd8-0676-40fa-932b-8d315c6e0d49 (Too many open files)+detailsjava.io.FileNotFoundException: /data/hadoop/yarn/local/usercache/hue/appcache/application_1568106731393_0586/blockmgr-d2b8076e-92c8-4f0c-a8a0-68b08b7b16de/21/temp_shuffle_f0801cd8-0676-40fa-932b-8d315c6e0d49 (Too many open files) 	at java.io.FileOutputStream.open0(Native Method) 	at java.io.FileOutputStream.open(FileOutputStream.java:270) 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) 	at org.apache.spark.storage.DiskBlockObjectWriter.initialize(DiskBlockObjectWriter.scala:103) 	at org.apache.spark.storage.DiskBlockObjectWriter.open(DiskBlockObjectWriter.scala:116) 	at org.apache.spark.storage.DiskBlockObjectWriter.write(DiskBlockObjectWriter.scala:237) 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:151) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53) 	at org.apache.spark.scheduler.Task.run(Task.scala:109) 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 	at java.lang.Thread.run(Thread.java:745)
--

How to solve it? What's the reason?
